#!/usr/bin/env bash
#
#
VERSION="1.0.1"
sudo cp /etc/iptables/rules.v4 /etc/iptables/rules.v4.previous
sudo cp /etc/iptables/rules.v6 /etc/iptables/rules.v6.previous
sudo cp -f nexus-iptables/rules.v? /etc/iptables/
sudo iptables-restore < /etc/iptables/rules.v4
sudo ip6tables-restore < /etc/iptables/rules.v6
exit 0